"""empty message

Revision ID: 284d9a636fb6
Revises: 9fb9db0b2bcc
Create Date: 2021-08-03 12:01:41.198587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284d9a636fb6'
down_revision = '9fb9db0b2bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbsd_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cbsd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('cbsd_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('fcc_id', sa.String(), nullable=True),
    sa.Column('cbsd_serial_number', sa.String(), nullable=True),
    sa.Column('eirp_capability', sa.Float(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['cbsd_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_mode_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cbsd_id', sa.Integer(), nullable=False),
    sa.Column('desired_state_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cbsd_id'], ['cbsd.id'], ),
    sa.ForeignKeyConstraint(['desired_state_id'], ['cbsd_state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cbsd_id')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cbsd_id', sa.Integer(), nullable=True),
    sa.Column('low_frequency', sa.Integer(), nullable=False),
    sa.Column('high_frequency', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('rule_applied', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cbsd_id'], ['cbsd.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('grant', sa.Column('last_heartbeat_request_time', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('grant', 'cbsd_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'grant', 'cbsd', ['cbsd_id'], ['id'])
    op.alter_column('request', 'cbsd_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'request', 'cbsd', ['cbsd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.alter_column('request', 'cbsd_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'grant', type_='foreignkey')
    op.alter_column('grant', 'cbsd_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('grant', 'last_heartbeat_request_time')
    op.drop_table('channel')
    op.drop_table('active_mode_config')
    op.drop_table('cbsd')
    op.drop_table('cbsd_state')
    # ### end Alembic commands ###
